from __future__ import annotations

from .models import ModelSpec


MODEL_CATALOG: list[ModelSpec] = [
    ModelSpec(
        id="u2net",
        title="U2Net",
        category="general",
        quality_tier="high",
        speed_tier="medium",
        license_class="personal-use-review",
        license_note="Recommended for personal use after checking the upstream weight and dataset source.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="u2netp",
        title="U2NetP",
        category="general",
        quality_tier="medium",
        speed_tier="very-high",
        license_class="personal-use-review",
        license_note="Common fallback model for personal use, but still review the upstream weight source.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="u2net_human_seg",
        title="U2Net Human Seg",
        category="portrait",
        quality_tier="medium",
        speed_tier="high",
        license_class="personal-use-review",
        license_note="Useful portrait fallback for personal use, with source review still recommended.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="u2net_cloth_seg",
        title="U2Net Cloth Seg",
        category="portrait",
        quality_tier="high",
        speed_tier="medium",
        license_class="personal-use-review",
        license_note="Useful for cloth parsing in personal workflows; the model source still deserves review.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="silueta",
        title="Silueta",
        category="general",
        quality_tier="medium",
        speed_tier="high",
        license_class="personal-use-review",
        license_note="Smaller model for faster personal-use fallback scenarios; review the source before redistribution.",
        recommended_backends=["directml", "cuda", "tensorrt", "cpu"],
    ),
    ModelSpec(
        id="isnet-general-use",
        title="ISNet General Use",
        category="general",
        quality_tier="high",
        speed_tier="high",
        license_class="personal-use-review",
        license_note="Strong all-around option for personal use; a source-license check is still recommended.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="isnet-anime",
        title="ISNet Anime",
        category="anime",
        quality_tier="high",
        speed_tier="high",
        license_class="personal-use-review",
        license_note="Check the model card and source terms before redistributing outside your own personal workflow.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="sam",
        title="SAM",
        category="general",
        quality_tier="premium",
        speed_tier="low",
        license_class="personal-use-review",
        license_note="SAM is flexible but heavier; review the upstream terms before wider redistribution.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="birefnet-general",
        title="BiRefNet General",
        category="detail",
        quality_tier="premium",
        speed_tier="medium",
        license_class="personal-use-review",
        license_note="Excellent quality for personal use, but the upstream source should still be reviewed.",
        recommended_backends=["directml", "cuda", "tensorrt", "cpu"],
    ),
    ModelSpec(
        id="birefnet-general-lite",
        title="BiRefNet General Lite",
        category="detail",
        quality_tier="high",
        speed_tier="medium",
        license_class="personal-use-review",
        license_note="Review upstream model weights and dataset source before broader redistribution.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="birefnet-portrait",
        title="BiRefNet Portrait",
        category="portrait",
        quality_tier="premium",
        speed_tier="medium",
        license_class="personal-use-review",
        license_note="Strong portrait quality for personal use, though the upstream model source still needs review.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="birefnet-dis",
        title="BiRefNet DIS",
        category="detail",
        quality_tier="premium",
        speed_tier="medium",
        license_class="personal-use-review",
        license_note="Specialized segmentation model; confirm the source dataset terms before sharing more broadly.",
        recommended_backends=["directml", "cuda", "tensorrt", "cpu"],
    ),
    ModelSpec(
        id="birefnet-hrsod",
        title="BiRefNet HRSOD",
        category="detail",
        quality_tier="premium",
        speed_tier="medium",
        license_class="personal-use-review",
        license_note="High-resolution salient object model; treat it as review-required before redistribution.",
        recommended_backends=["directml", "cuda", "tensorrt", "cpu"],
    ),
    ModelSpec(
        id="birefnet-cod",
        title="BiRefNet COD",
        category="detail",
        quality_tier="high",
        speed_tier="medium",
        license_class="personal-use-review",
        license_note="Concealed object model with niche use; still worth checking the upstream license details.",
        recommended_backends=["directml", "cuda", "tensorrt", "cpu"],
    ),
    ModelSpec(
        id="birefnet-massive",
        title="BiRefNet Massive",
        category="detail",
        quality_tier="premium",
        speed_tier="low",
        license_class="personal-use-review",
        license_note="Large, high-quality model suited to personal use; verify redistribution rights before sharing.",
        recommended_backends=["directml", "cuda", "tensorrt", "cpu"],
    ),
    ModelSpec(
        id="bria-rmbg",
        title="BRIA RMBG",
        category="general",
        quality_tier="premium",
        speed_tier="high",
        license_class="personal-use-restricted",
        license_note="For personal use, please still check BRIA's official terms before broader use or redistribution.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
]


MODEL_MAP = {model.id: model for model in MODEL_CATALOG}
