from __future__ import annotations

from .models import ModelSpec


MODEL_CATALOG: list[ModelSpec] = [
    ModelSpec(
        id="u2net",
        title="U2Net",
        category="general",
        quality_tier="high",
        speed_tier="medium",
        license_class="commercial-review",
        license_note="Audit the upstream weight and dataset terms before bundling in a paid product.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="u2netp",
        title="U2NetP",
        category="general",
        quality_tier="medium",
        speed_tier="very-high",
        license_class="commercial-review",
        license_note="Common fallback model, but still verify the redistributed weight license.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="u2net_human_seg",
        title="U2Net Human Seg",
        category="portrait",
        quality_tier="medium",
        speed_tier="high",
        license_class="commercial-review",
        license_note="Useful portrait fallback, but upstream licensing still needs review.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="u2net_cloth_seg",
        title="U2Net Cloth Seg",
        category="portrait",
        quality_tier="high",
        speed_tier="medium",
        license_class="commercial-review",
        license_note="Cloth parsing is valuable commercially, but the model source still requires audit.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="silueta",
        title="Silueta",
        category="general",
        quality_tier="medium",
        speed_tier="high",
        license_class="commercial-review",
        license_note="Smaller model for faster fallback scenarios; verify weight redistribution rights.",
        recommended_backends=["directml", "cuda", "tensorrt", "cpu"],
    ),
    ModelSpec(
        id="isnet-general-use",
        title="ISNet General Use",
        category="general",
        quality_tier="high",
        speed_tier="high",
        license_class="commercial-review",
        license_note="Strong all-around option, but still needs a source-license check before shipping.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="isnet-anime",
        title="ISNet Anime",
        category="anime",
        quality_tier="high",
        speed_tier="high",
        license_class="commercial-review",
        license_note="Check model card and source license before bundling in a paid desktop app.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="sam",
        title="SAM",
        category="general",
        quality_tier="premium",
        speed_tier="low",
        license_class="commercial-review",
        license_note="SAM is flexible but heavier; review Meta's current commercial terms for your distribution plan.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="birefnet-general",
        title="BiRefNet General",
        category="detail",
        quality_tier="premium",
        speed_tier="medium",
        license_class="commercial-review",
        license_note="Excellent quality, but verify source licensing before product inclusion.",
        recommended_backends=["directml", "cuda", "tensorrt", "cpu"],
    ),
    ModelSpec(
        id="birefnet-general-lite",
        title="BiRefNet General Lite",
        category="detail",
        quality_tier="high",
        speed_tier="medium",
        license_class="commercial-review",
        license_note="Review upstream model weights and dataset license before product distribution.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="birefnet-portrait",
        title="BiRefNet Portrait",
        category="portrait",
        quality_tier="premium",
        speed_tier="medium",
        license_class="commercial-review",
        license_note="Strong portrait quality, but the upstream model license still needs audit.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
    ModelSpec(
        id="birefnet-dis",
        title="BiRefNet DIS",
        category="detail",
        quality_tier="premium",
        speed_tier="medium",
        license_class="commercial-review",
        license_note="Specialized segmentation model; confirm its source dataset terms before sale.",
        recommended_backends=["directml", "cuda", "tensorrt", "cpu"],
    ),
    ModelSpec(
        id="birefnet-hrsod",
        title="BiRefNet HRSOD",
        category="detail",
        quality_tier="premium",
        speed_tier="medium",
        license_class="commercial-review",
        license_note="High-resolution salient object model; treat it as review-required before distribution.",
        recommended_backends=["directml", "cuda", "tensorrt", "cpu"],
    ),
    ModelSpec(
        id="birefnet-cod",
        title="BiRefNet COD",
        category="detail",
        quality_tier="high",
        speed_tier="medium",
        license_class="commercial-review",
        license_note="Concealed object model with niche use; still requires license verification.",
        recommended_backends=["directml", "cuda", "tensorrt", "cpu"],
    ),
    ModelSpec(
        id="birefnet-massive",
        title="BiRefNet Massive",
        category="detail",
        quality_tier="premium",
        speed_tier="low",
        license_class="commercial-review",
        license_note="Large, high-quality model; verify allowed redistribution before monetizing.",
        recommended_backends=["directml", "cuda", "tensorrt", "cpu"],
    ),
    ModelSpec(
        id="bria-rmbg",
        title="BRIA RMBG",
        category="general",
        quality_tier="premium",
        speed_tier="high",
        license_class="commercial-agreement-required",
        license_note="Commercial distribution should use BRIA's commercial terms or API/package agreement.",
        recommended_backends=["directml", "cuda", "tensorrt", "openvino", "cpu"],
    ),
]


MODEL_MAP = {model.id: model for model in MODEL_CATALOG}
